function structname=create_su_struct();

% This function creates a matlab struct containing the 
% su header words as fields and an additional field 'trace'
% for the actual seismogram trace. 
%
% All fields are set to zero apart from
%    .trid=1	(seismic trace)
%    .scalel=1 
%    .scalco=1
%    .counit=1
%    .gain=1
%    .igc=1
%    .igi=1
%    .corr=1	(uncorrelated traces)	 


structname = struct('tracl',0,...
                    'tracr',0,...
		    'fldr',0,...
		    'tracf',0,...
		    'ep',0,...
		    'cdp',0,...
		    'cdpt',0,...
		    'trid',1,...
		    'nvs',0,...
		    'nhs',0,...
		    'duse',0,...
		    'offset',0,...
		    'gelev',0,...
		    'selev',0,...
		    'sdepth',0,...
		    'gdel',0,...
		    'sdel',0,...
		    'swdep',0,...
		    'gwdep',0,...
		    'scalel',1,...
		    'scalco',1,...
		    'sx',0,...
		    'sy',0,...
		    'gx',0,...
		    'gy',0,...
		    'counit',1,...
		    'wevel',0,...
		    'swevel',0,...
		    'sut',0,...
		    'gut',0,...
		    'sstat',0,...
		    'gstat',0,...
		    'tstat',0,...
		    'laga',0,...
		    'lagb',0,...
		    'delrt',0,...
		    'muts',0,...
		    'mute',0,...
		    'ns',0,...
		    'dt',0,...
		    'gain',1,...
		    'igc',1,...
		    'igi',1,...
		    'corr',1,...
		    'sfs',0,...
		    'sfe',0,...
		    'slen',0,...
		    'styp',0,...
		    'stas',0,...
		    'stae',0,...
		    'tatyp',0,...
		    'afilf',0,...
		    'afils',0,...
		    'nofilf',0,...
		    'nofils',0,...
		    'lcf',0,...
		    'hcf',0,...
		    'lcs',0,...
		    'hcs',0,...
		    'year',0,...
		    'day',0,...
		    'hour',0,...
		    'minute',0,...
		    'sec',0,...
		    'timbas',0,...
		    'trwf',0,...
		    'grnors',0,...
		    'grnofr',0,...
		    'grnlof',0,...
		    'gaps',0,...
		    'otrav',0,...
		    'd1',0,...
		    'f1',0,...
		    'd2',0,...
		    'f2',0,...
		    'ungpow',0,...
		    'unscale',0,...
		    'ntr',0,...
		    'mark',0,...
		    'shortpad',0,...
		    'unass',0,...
		    'trace',0);
